version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    # image: amirpourmand/al-folio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
